savedcombo = global.savedcombo
comboscoremax = floor(((savedcombo^2) * 0.25) + (10 * savedcombo))
comboscore = comboscoremax
combominus = round(comboscoremax / 50)
timer_max = 1
timer = 0
alarm[0] = 1
title_index = 0.35
very = false
x = 832
y = 197
ystart = y
depth = -300